### ISSUE TITLE
Update-AzStorageAccountADObjectPassword: Exception calling "ShouldProcess" with "3" argument(s): "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by madde-g** [Azure-Samples/azure-files-samples#152]
Using v0.2.7
Running in PowerShell 7.3.6

```pwsh
Join-AzStorageAccountForAuth `
    -ResourceGroupName $resourceGroupName `
    -StorageAccountName $storageAccountName `
    -Domain $domain  `
    -DomainAccountType "ComputerAccount"  `
    -OrganizationalUnitDistinguishedName $ouDistinguishedName `
    -OverwriteExistingADObject `
    -EncryptionType "AES256" `
    -SamAccountName $samAccountName `
    -Verbose `
    -ErrorAction Stop
```

```pwsh
Update-AzStorageAccountADObjectPassword: Exception calling "ShouldProcess" with "3" argument(s): "Object reference not set to an instance of an object."
    + CategoryInfo          : NotSpecified: (Update-A...an object.":String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    + PSComputerName        : localhost
```

**Comment by a8ree** [comment]
I'm getting something similar when trying to execute this via a pipeline

16:00:38   Info     |       System.Management.Automation.MethodInvocationException: Exception calling "ShouldProcess" with "3" argument(s): "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available." ---> System.Management.Automation.PSInvalidOperationException: Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
16:00:38   Info     |       at Microsoft.PowerShell.ConsoleHostUserInterface.HandleThrowOnReadAndPrompt()
16:00:38   Info     |       at Microsoft.PowerShell.ConsoleHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)

I've noticed that a dialogue is shown when run interactively

@madde-g are you running interactively???

**Comment by madde-g** [comment]
@a8ree I am not
